CREATE TABLE dbo.LOGISTICS_REQUEST_SOURCE_TYPE
(
    LOGISTICS_REQUEST_SOURCE_TYPE_ID BIGINT IDENTITY(1,1) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION NVARCHAR(150) NOT NULL,

    CREATE_USER BIGINT NOT NULL,
    CREATE_DATE DATETIME NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_SOURCE_TYPE_CREATE_DATE DEFAULT(GETDATE()),

    UPDATE_USER BIGINT NULL,
    UPDATE_DATE DATETIME NULL,

    STATUS BIT NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_SOURCE_TYPE_STATUS DEFAULT(1),

    CONSTRAINT PK_LOGISTICS_REQUEST_SOURCE_TYPE
        PRIMARY KEY (LOGISTICS_REQUEST_SOURCE_TYPE_ID),

    CONSTRAINT UQ_LOGISTICS_REQUEST_SOURCE_TYPE_CODE
        UNIQUE (CODE)
);

INSERT INTO dbo.LOGISTICS_REQUEST_SOURCE_TYPE
(
    CODE,
    DESCRIPTION,
    CREATE_USER,
    STATUS
)
VALUES
('APP_OPERATIONS',          'Aplicativo de operaciones', 1, 1),
('MANUAL_OFFICE',           'Solicitud manual de oficina', 1, 1),
('QUOTATION',               'Cotización principal', 1, 1),
('ADDITIONAL_QUOTATION',    'Cotización adicional', 1, 1),
('SYSTEM_SUGGESTION',       'Sugerencia generada por sistema', 1, 1);

CREATE TABLE dbo.LOGISTICS_REQUEST_STATUS
(
    LOGISTICS_REQUEST_STATUS_ID BIGINT IDENTITY(1,1) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION NVARCHAR(150) NOT NULL,

    CREATE_USER BIGINT NOT NULL,
    CREATE_DATE DATETIME NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_STATUS_CREATE_DATE DEFAULT(GETDATE()),

    UPDATE_USER BIGINT NULL,
    UPDATE_DATE DATETIME NULL,

    STATUS BIT NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_STATUS_STATUS DEFAULT(1),

    CONSTRAINT PK_LOGISTICS_REQUEST_STATUS
        PRIMARY KEY (LOGISTICS_REQUEST_STATUS_ID),

    CONSTRAINT UQ_LOGISTICS_REQUEST_STATUS_CODE
        UNIQUE (CODE)
);
INSERT INTO dbo.LOGISTICS_REQUEST_STATUS
(
    CODE,
    DESCRIPTION,
    CREATE_USER,
    STATUS
)
VALUES
('DRAFT',                  'Borrador', 1, 1),
('PENDING_OFFICE_REVIEW',  'Pendiente de revisión de oficina', 1, 1),
('OBSERVED',               'Observada', 1, 1),
('OFFICE_APPROVED',        'Aprobada por oficina', 1, 1),
('SENT_TO_LOGISTICS',      'Enviada a logística', 1, 1),
('RECEIVED_BY_LOGISTICS',  'Recibida por logística', 1, 1),
('IN_PROGRESS',            'En atención', 1, 1),
('PARTIALLY_ATTENDED',     'Atendida parcialmente', 1, 1),
('ATTENDED',               'Atendida', 1, 1),
('REJECTED',               'Rechazada', 1, 1),
('CANCELLED',              'Anulada', 1, 1);

CREATE TABLE dbo.LOGISTICS_REQUEST_DETAIL_STATUS
(
    LOGISTICS_REQUEST_DETAIL_STATUS_ID BIGINT IDENTITY(1,1) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION NVARCHAR(150) NOT NULL,

    CREATE_USER BIGINT NOT NULL,
    CREATE_DATE DATETIME NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_STATUS_CREATE_DATE DEFAULT(GETDATE()),

    UPDATE_USER BIGINT NULL,
    UPDATE_DATE DATETIME NULL,

    STATUS BIT NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_STATUS_STATUS DEFAULT(1),

    CONSTRAINT PK_LOGISTICS_REQUEST_DETAIL_STATUS
        PRIMARY KEY (LOGISTICS_REQUEST_DETAIL_STATUS_ID),

    CONSTRAINT UQ_LOGISTICS_REQUEST_DETAIL_STATUS_CODE
        UNIQUE (CODE)
);

INSERT INTO dbo.LOGISTICS_REQUEST_DETAIL_STATUS
(
    CODE,
    DESCRIPTION,
    CREATE_USER,
    STATUS
)
VALUES
('PENDING',              'Pendiente', 1, 1),
('APPROVED',             'Aprobado', 1, 1),
('OBSERVED',             'Observado', 1, 1),
('REJECTED',             'Rechazado', 1, 1),
('IN_PROGRESS',          'En atención', 1, 1),
('PARTIALLY_ATTENDED',   'Atendido parcialmente', 1, 1),
('ATTENDED',             'Atendido', 1, 1),
('PENDING_PURCHASE',     'Pendiente de compra', 1, 1),
('PENDING_RENTAL',       'Pendiente de alquiler', 1, 1),
('CANCELLED',            'Cancelado', 1, 1),
('CLOSED_WITH_DIFFERENCE','Cerrado con diferencia', 1, 1);

CREATE TABLE dbo.LOGISTICS_REQUEST
(
    LOGISTICS_REQUEST_ID BIGINT IDENTITY(1,1) NOT NULL,
    BUSINESS_ID BIGINT NOT NULL,

    REQUEST_NUMBER NVARCHAR(50) NOT NULL,

    -- Relación con comercial / operación
    OPPOR_ID BIGINT NULL,
    QUOTATION_ID BIGINT NULL,
    QUOTATION_VER_ID BIGINT NULL,

    -- Origen de la solicitud
    LOGISTICS_REQUEST_SOURCE_TYPE_ID BIGINT NOT NULL,

    -- Estado de la solicitud
    LOGISTICS_REQUEST_STATUS_ID BIGINT NOT NULL,

    -- Usuario que solicita
    REQUESTED_BY BIGINT NOT NULL,
    REQUEST_DATE DATETIME NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_REQUEST_DATE DEFAULT(GETDATE()),

    -- Revisión de oficina
    REVIEWED_BY BIGINT NULL,
    REVIEWED_DATE DATETIME NULL,

    -- Envío a logística
    SENT_TO_LOGISTICS_BY BIGINT NULL,
    SENT_TO_LOGISTICS_DATE DATETIME NULL,

    -- Recepción por logística
    RECEIVED_BY_LOGISTICS_BY BIGINT NULL,
    RECEIVED_BY_LOGISTICS_DATE DATETIME NULL,

    OBSERVATION NVARCHAR(500) NULL,
    OFFICE_OBSERVATION NVARCHAR(500) NULL,
    LOGISTICS_OBSERVATION NVARCHAR(500) NULL,

    CREATE_USER BIGINT NOT NULL,
    CREATE_DATE DATETIME NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_CREATE_DATE DEFAULT(GETDATE()),

    UPDATE_USER BIGINT NULL,
    UPDATE_DATE DATETIME NULL,

    STATUS BIT NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_STATUS DEFAULT(1),

    CONSTRAINT PK_LOGISTICS_REQUEST
        PRIMARY KEY (LOGISTICS_REQUEST_ID),

    CONSTRAINT UQ_LOGISTICS_REQUEST_NUMBER
        UNIQUE (BUSINESS_ID, REQUEST_NUMBER),

    CONSTRAINT FK_LOGISTICS_REQUEST_BUSINESS
        FOREIGN KEY (BUSINESS_ID) 
        REFERENCES dbo.BUSINESS(ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_QUOTATION
        FOREIGN KEY (QUOTATION_ID) 
        REFERENCES dbo.SALES_QUOTATION_HDR(QUOTATION_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_QUOTATION_VER
        FOREIGN KEY (QUOTATION_VER_ID) 
        REFERENCES dbo.SALES_QUOTATION_VER_HDR(QUOTATION_VER_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_SOURCE_TYPE
        FOREIGN KEY (LOGISTICS_REQUEST_SOURCE_TYPE_ID)
        REFERENCES dbo.LOGISTICS_REQUEST_SOURCE_TYPE(LOGISTICS_REQUEST_SOURCE_TYPE_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_STATUS
        FOREIGN KEY (LOGISTICS_REQUEST_STATUS_ID)
        REFERENCES dbo.LOGISTICS_REQUEST_STATUS(LOGISTICS_REQUEST_STATUS_ID)
);

CREATE TABLE dbo.LOGISTICS_REQUEST_DETAIL
(
    LOGISTICS_REQUEST_DETAIL_ID BIGINT IDENTITY(1,1) NOT NULL,
    BUSINESS_ID BIGINT NOT NULL,
    LOGISTICS_REQUEST_ID BIGINT NOT NULL,

    -- Producto puede ser NULL si es una sugerencia libre/manual todavía no registrada como producto
    PRODUCTS_ID BIGINT NULL,

    DESCRIPTION NVARCHAR(500) NOT NULL,

    -- MATERIAL / TOOL / EQUIPMENT / EPP / CONSUMABLE / SERVICE
    LOGISTICS_RESOURCE_TYPE_ID BIGINT NOT NULL,

    UOM_ID BIGINT NULL,
    WAREHOUSE_ID BIGINT NULL,

    -- Cantidades
    REQUESTED_QUANTITY DECIMAL(18,4) NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_REQUESTED_QTY DEFAULT(0),

    APPROVED_QUANTITY DECIMAL(18,4) NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_APPROVED_QTY DEFAULT(0),

    RESERVED_QUANTITY DECIMAL(18,4) NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_RESERVED_QTY DEFAULT(0),

    ATTENDED_QUANTITY DECIMAL(18,4) NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_ATTENDED_QTY DEFAULT(0),

    CANCELLED_QUANTITY DECIMAL(18,4) NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_CANCELLED_QTY DEFAULT(0),

    PENDING_QUANTITY AS 
        (
            APPROVED_QUANTITY 
            - ATTENDED_QUANTITY 
            - CANCELLED_QUANTITY
        ) PERSISTED,

    -- Compra / alquiler si no hay stock
    NEEDS_PURCHASE BIT NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_NEEDS_PURCHASE DEFAULT(0),

    NEEDS_RENTAL BIT NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_NEEDS_RENTAL DEFAULT(0),

    -- Estado por línea
    LOGISTICS_REQUEST_DETAIL_STATUS_ID BIGINT NOT NULL,

    -- Trazabilidad desde cotización/sugerencia
    SOURCE_QUOTATION_VER_LIN_ID BIGINT NULL,
    SOURCE_SUGGESTION_ID BIGINT NULL,

    -- Movimiento o despacho futuro
    WAREHOUSE_MOVEMENT_ID BIGINT NULL,

    OBSERVATION NVARCHAR(500) NULL,
    LOGISTICS_OBSERVATION NVARCHAR(500) NULL,

    CREATE_USER BIGINT NOT NULL,
    CREATE_DATE DATETIME NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_CREATE_DATE DEFAULT(GETDATE()),

    UPDATE_USER BIGINT NULL,
    UPDATE_DATE DATETIME NULL,

    STATUS BIT NOT NULL 
        CONSTRAINT DF_LOGISTICS_REQUEST_DETAIL_STATUS DEFAULT(1),

    CONSTRAINT PK_LOGISTICS_REQUEST_DETAIL
        PRIMARY KEY (LOGISTICS_REQUEST_DETAIL_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_BUSINESS
        FOREIGN KEY (BUSINESS_ID) 
        REFERENCES dbo.BUSINESS(ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_REQUEST
        FOREIGN KEY (LOGISTICS_REQUEST_ID) 
        REFERENCES dbo.LOGISTICS_REQUEST(LOGISTICS_REQUEST_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_PRODUCT
        FOREIGN KEY (PRODUCTS_ID) 
        REFERENCES dbo.PRODUCTS(PRODUCTS_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_RESOURCE_TYPE
        FOREIGN KEY (LOGISTICS_RESOURCE_TYPE_ID)
        REFERENCES dbo.LOGISTICS_RESOURCE_TYPE(LOGISTICS_RESOURCE_TYPE_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_UOM
        FOREIGN KEY (UOM_ID) 
        REFERENCES dbo.UNIT_OF_MEASURE(UOM_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_WAREHOUSE
        FOREIGN KEY (WAREHOUSE_ID) 
        REFERENCES dbo.WAREHOUSES(WAREHOUSES_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_STATUS
        FOREIGN KEY (LOGISTICS_REQUEST_DETAIL_STATUS_ID)
        REFERENCES dbo.LOGISTICS_REQUEST_DETAIL_STATUS(LOGISTICS_REQUEST_DETAIL_STATUS_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_QUOTATION_LINE
        FOREIGN KEY (SOURCE_QUOTATION_VER_LIN_ID)
        REFERENCES dbo.SALES_QUOTATION_VER_LIN(QUOTATION_VER_LIN_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_SUGGESTION
        FOREIGN KEY (SOURCE_SUGGESTION_ID)
        REFERENCES dbo.QUOTATION_LOGISTICS_SUGGESTION(QUOTATION_LOGISTICS_SUGGESTION_ID),

    CONSTRAINT FK_LOGISTICS_REQUEST_DETAIL_WAREHOUSE_MOVEMENT
        FOREIGN KEY (WAREHOUSE_MOVEMENT_ID)
        REFERENCES dbo.WAREHOUSE_MOVEMENT(WAREHOUSE_MOVEMENT_ID),

    CONSTRAINT CK_LOGISTICS_REQUEST_DETAIL_REQUESTED_QTY
        CHECK (REQUESTED_QUANTITY >= 0),

    CONSTRAINT CK_LOGISTICS_REQUEST_DETAIL_APPROVED_QTY
        CHECK (APPROVED_QUANTITY >= 0),

    CONSTRAINT CK_LOGISTICS_REQUEST_DETAIL_RESERVED_QTY
        CHECK (RESERVED_QUANTITY >= 0),

    CONSTRAINT CK_LOGISTICS_REQUEST_DETAIL_ATTENDED_QTY
        CHECK (ATTENDED_QUANTITY >= 0),

    CONSTRAINT CK_LOGISTICS_REQUEST_DETAIL_CANCELLED_QTY
        CHECK (CANCELLED_QUANTITY >= 0),

    CONSTRAINT CK_LOGISTICS_REQUEST_DETAIL_ATTENDED_NOT_GREATER
        CHECK (ATTENDED_QUANTITY <= APPROVED_QUANTITY),

    CONSTRAINT CK_LOGISTICS_REQUEST_DETAIL_CANCELLED_NOT_GREATER
        CHECK (CANCELLED_QUANTITY <= APPROVED_QUANTITY)
);

CREATE INDEX IX_LOGISTICS_REQUEST_BUSINESS_STATUS
ON dbo.LOGISTICS_REQUEST
(
    BUSINESS_ID,
    LOGISTICS_REQUEST_STATUS_ID,
    STATUS
);

CREATE INDEX IX_LOGISTICS_REQUEST_QUOTATION
ON dbo.LOGISTICS_REQUEST
(
    BUSINESS_ID,
    QUOTATION_ID,
    QUOTATION_VER_ID,
    STATUS
);

CREATE INDEX IX_LOGISTICS_REQUEST_SOURCE_TYPE
ON dbo.LOGISTICS_REQUEST
(
    BUSINESS_ID,
    LOGISTICS_REQUEST_SOURCE_TYPE_ID,
    STATUS
);

CREATE INDEX IX_LOGISTICS_REQUEST_DETAIL_REQUEST
ON dbo.LOGISTICS_REQUEST_DETAIL
(
    BUSINESS_ID,
    LOGISTICS_REQUEST_ID,
    STATUS
);

CREATE INDEX IX_LOGISTICS_REQUEST_DETAIL_PRODUCT
ON dbo.LOGISTICS_REQUEST_DETAIL
(
    BUSINESS_ID,
    PRODUCTS_ID,
    STATUS
);

CREATE INDEX IX_LOGISTICS_REQUEST_DETAIL_SOURCE_SUGGESTION
ON dbo.LOGISTICS_REQUEST_DETAIL
(
    BUSINESS_ID,
    SOURCE_SUGGESTION_ID,
    STATUS
);

CREATE INDEX IX_LOGISTICS_REQUEST_DETAIL_QUOTATION_LINE
ON dbo.LOGISTICS_REQUEST_DETAIL
(
    BUSINESS_ID,
    SOURCE_QUOTATION_VER_LIN_ID,
    STATUS
);

CREATE INDEX IX_LOGISTICS_REQUEST_DETAIL_STATUS
ON dbo.LOGISTICS_REQUEST_DETAIL
(
    BUSINESS_ID,
    LOGISTICS_REQUEST_DETAIL_STATUS_ID,
    STATUS
);